import pydicom, random
from pydicom.dataset import Dataset, FileMetaDataset
from pydicom.sequence import Sequence

# UID obtained from Medical Connections on Oct 5 2021, 22:37
COOL_CT_ROOT_UID = '1.2.826.0.1.3680043.10.827'

def save_dicom(image_data, output_file, patient_name):
    # File meta info data elements
    file_meta = FileMetaDataset()
    file_meta.FileMetaInformationVersion = b'\x00\x01'

    instance_uid = pydicom.uid.generate_uid()

    # Computed Tomography Image IOD
    # http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_A.3.html
    file_meta.MediaStorageSOPClassUID = '1.2.840.10008.5.1.4.1.1.2'
    file_meta.MediaStorageSOPInstanceUID = instance_uid 
    
    # Set Transfer Syntax UID as per:
    # http://dicom.nema.org/medical/dicom/2014c/output/chtml/part18/sect_8.2.11.html
    file_meta.TransferSyntaxUID = pydicom.uid.ExplicitVRLittleEndian

    file_meta.ImplementationClassUID = COOL_CT_ROOT_UID + '.1'
    file_meta.ImplementationVersionName = 'cool_ct'

    image_rows, image_cols = image_data.shape

    # Main data elements
    ds = Dataset()
    ds.ImageType = ['ORIGINAL', 'PRIMARY', 'AXIAL']
    ds.SOPClassUID = file_meta.MediaStorageSOPClassUID 
    ds.SOPInstanceUID = instance_uid 
    ds.Modality = 'CT'
    ds.PatientName = patient_name
    ds.PatientID = str(random.randrange(1,100))
    ds.StudyInstanceUID = pydicom.uid.generate_uid() 
    ds.SeriesInstanceUID = pydicom.uid.generate_uid()
    ds.InstanceNumber = '1'
    ds.FrameOfReferenceUID = pydicom.uid.generate_uid()
    ds.ImagesInAcquisition = '1'
    ds.ImageComments = 'Fake scan generated by cool_ct'
    ds.SamplesPerPixel = 1
    ds.PhotometricInterpretation = 'MONOCHROME2'
    ds.Rows = image_rows
    ds.Columns = image_cols
    ds.BitsAllocated = 8
    ds.BitsStored = 8
    ds.HighBit = 7
    ds.PixelRepresentation = 0
    ds.PixelData = image_data.tobytes()

    ds.file_meta = file_meta
    ds.is_implicit_VR = False
    ds.is_little_endian = True
    ds.save_as(output_file, write_like_original=False)
